export const SELECT_WORD = "SELECT_WORD";
export const SIGHT_SEEN= "SIGHT_SEEN";
export const SET_WORDS= "SET_WORDS";
export const USER_NAME= "USER_NAME";
export const PASSWORD= "PASSWORD";
export const NEW_USER= "NEW_USER";
export const LOGGED= "LOGGED";
export const VICTORY= "VICTORY";
export const SCORE= "SCORE";
export const RESET="RESET"
export const POINT_SCORED="POINT_SCORED"
export const CLOSE_MODAL="CLOSE_MODAL"
